system:
  prefix: '&a&lElectroHub &7» '

world:
  spawn-point: []

physics:
  double-jump:
    enabled: true
    velocity-strength: 1.5
    particle: CLOUD

launch-pad:
  pad:
    enabled: true
    velocity-strength: 1

sound:
  commands:
    rejected: BLOCK_NOTE_BLOCK_BASS
    allowed: BLOCK_NOTE_BLOCK_PLING
    double-jump: ENTITY_GENERIC_EXPLODE
    launch-pad: ENTITY_EGG_THROW
  