system:
  prefix: '&a&lElectroHub &7» '

world:
  spawn-point: []

physics:
  double-jump:
    enabled: true
    velocity-strength: 1.5
    particle: SPELL_WITCH

sound:
  commands:
    rejected: BLOCK_NOTE_BLOCK_BASS 0
    allowed: BLOCK_NOTE_BLOCK_PLING 2
  double-jump: ENTITY_FIREWORK_ROCKET_LAUNCH 1
  