name: Electrohub
version: '${version}'
main: dev.justnotro.electrohub.Electrohub
authors: [ JustNOTRO, OfirTIM ]
description: Electrifying Hub Experience 

commands:
  fly:
    description: Set a player flight ability. ×“